### ISSUE TITLE
User Story 1: As a user, I would like to create a deposit account.

### ISSUE THREAD

**Issue by francis-pouatcha** [ADORSYS-GIS/webank#56]
Subtasks
- [ ] ADORSYS-GIS/webank#59 
- [ ] ADORSYS-GIS/webank-OnlineBanking#31 
- [ ] ADORSYS-GIS/webank#61 
- [ ] ADORSYS-GIS/webank#62 
- [ ] ADORSYS-GIS/webank#70 
- [ ] ADORSYS-GIS/webank#71
