### ISSUE TITLE
WB003: Access Management Service

### ISSUE THREAD

**Issue by francis-pouatcha** [ADORSYS-GIS/webank#61]
# Description
For this MVP, we need the possibility of associating a bank account with a device that is allowed to access the bank account.

- ## Subtasks

- [ ] ADORSYS-GIS/webank-OnlineBanking#14
- [ ] ADORSYS-GIS/webank-OnlineBanking#16
- [ ] ADORSYS-GIS/webank-OnlineBanking#17
- [ ] ADORSYS-GIS/webank-OnlineBanking#15
