### ISSUE TITLE
WB004: SMS Gateway Service

### ISSUE THREAD

**Issue by hanswizzy** [ADORSYS-GIS/webank#62]
## Subtask of
- ADORSYS-GIS/webank-OnlineBanking#56
## Subtasks
- [ ] ADORSYS-GIS/webank-OnlineBanking#9
- [ ] ADORSYS-GIS/webank-OnlineBanking#26
- [ ] ADORSYS-GIS/webank-OnlineBanking#32
- [ ] ADORSYS-GIS/webank-pending-registration-service#9
