### ISSUE TITLE
WB010: Pending Registration Service

### ISSUE THREAD

**Issue by nancymuyeh** [ADORSYS-GIS/webank#71]
## Subtask of
- ADORSYS-GIS/webank-OnlineBanking#56
## Subtasks

- [ ] ADORSYS-GIS/webank-pending-registration-service#3
- [ ] ADORSYS-GIS/webank-pending-registration-service#5
- [ ] ADORSYS-GIS/webank-pending-registration-service#1
- [ ] ADORSYS-GIS/webank-pending-registration-service#4
- [ ] ADORSYS-GIS/webank-pending-registration-service#18
